<h3><?php echo sprintf($this->translate('Change Password for %s'), $this->zfcUserDisplayName()); ?></h3>
<?php if ($status === true) : ?>
<div class="alert alert-success"><?php echo $this->translate('Password changed successfully.');?></div>
<?php elseif ($status === false) : ?>
<div class="alert alert-error"><?php echo $this->translate('Unable to update your password. Please try again.'); ?></div>
<?php endif; ?>
<?php

$form = $this->changePasswordForm;

$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/changepassword'));
$form->setAttribute('method', 'post');

$emailElement = $form->get('identity');
$emailElement->setValue($this->zfcUserIdentity()->getEmail());

echo $this->form()->openTag($form);

$submitLabel = $form->get('submit')->getLabel();
$form->remove('submit');
$elms = $form->getElements();
foreach($elms as $k => $element){
	/* @var $element \Zend\Form\Element */
	$element
		->setOption('column-size', 'sm-9')
		->setOption('label', $element->getLabel())
		->setLabelAttributes(array('class' => 'col-sm-3'));
}

$form->add(array(
	'name' => 'submit',
	'type' => 'Submit',
	'options' => array(
		'as-group' => true,
	),
	'attributes' => array(
		'value' => $submitLabel ?: 'Submit' ,
		'class' => 'btn-success',
	)
));

echo $this->twbForm($form);
