<h3><?php echo sprintf($this->translate('Change Email for %s'), $this->zfcUserDisplayName()); ?></h3>
<?php if ($status === true) : ?>
<div class="alert alert-success"><?php echo $this->translate('Email address changed successfully.'); ?></div>
<?php elseif ($status === false) : ?>
<div class="alert alert-error"><?php echo $this->translate('Unable to update your email address. Please try again.'); ?></div>
<?php endif; ?>
<?php

$form = $this->changeEmailForm;

$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/changeemail'));
$form->setAttribute('method', 'post');

if($this->redirect){
	$form->add(array(
		'name' => 'redirect',
		'type' => 'Hidden',
		'attributes' => array(
			'value' => $this->redirect
		)
	));
}

$elms = $form->getElements();
foreach($elms as $k => $element){
	/* @var $element \Zend\Form\Element */
	$element
		->setOption('column-size', 'sm-9')
		->setOption('label', $element->getLabel())
		->setLabelAttributes(array('class' => 'col-sm-3'));
}

$form->add(array(
	'name' => 'submit',
	'type' => 'Submit',
	'options' => array(
		'as-group' => true,
	),
	'attributes' => array(
		'value' => 'Senden',
		'class' => 'btn-success',
	)
));

echo $this->twbForm($form);