<?php

if($this->success): ?>
	<h1><?php echo $this->translate('Thank you!'); ?></h1>
	<?php if($this->activated): ?>
	<p><?php echo $this->translate('Your email has been successfully verified. You can sign in now!'); ?></p>
	<?php else : ?>
	<p><?php echo $this->translate('Your email has been successfully verified, but your account has to be confirmed by a moderator befor you can sign in. <br>You will be notified when your account is activated.'); ?></p>
	<?php endif; ?>
<?php else : ?>
	<h1><?php echo $this->translate('Whoops..'); ?></h1>
	<p><?php echo $this->translate('Email verification failed for the following reason: ') ?><?php echo $this->translate($this->message); ?></p>
<?php endif;