<h1><?php echo $this->translate('Sign In'); ?></h1>

<?php
$form = $this->loginForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/login'));
$form->setAttribute('method', 'post');

/* @var $form \Zend\Form\Form */
if($this->redirect){
	$form->add(array(
		'name' => 'redirect',
		'type' => 'Hidden',
		'attributes' => array(
			'value' => $this->redirect
		)
	));
}

$submitLabel = $form->get('submit')->getLabel();
$form->remove('submit');
$elms = $form->getElements();
foreach($elms as $k => $element){
	/* @var $element \Zend\Form\Element */
	$element
		->setOption('column-size', 'sm-10')
		->setOption('label', $element->getLabel())
		->setLabelAttributes(array('class' => 'col-sm-2'));
}

$form->add(array(
	'name' => 'submit',
	'type' => 'Submit',
	'options' => array(
		'as-group' => true,
	),
	'attributes' => array(
		'value' => $submitLabel,
		'class' => 'btn-success',
	)
));

echo $this->flashMessenger()->render(Zend\Mvc\Controller\Plugin\FlashMessenger::NAMESPACE_SUCCESS);

echo $this->formElementErrors($form->get('identity'));

echo $this->twbForm($form);

?>
<p><a href="<?php echo $this->url('zfcuser/forgotpassword') ?>"><?php echo $this->translate("Forgot your password?"); ?></a></p>
<?php if ($this->enableRegistration) : ?>
<?php echo $this->translate('Not registered?'); ?> <a href="<?php echo $this->url('zfcuser/register') . ($this->redirect ? '?redirect='.$this->escapeUrl($this->redirect) : '') ?>"><?php echo $this->translate('Sign up!'); ?></a>
<?php endif; 