<?php

use SkelletonApplication\Options\SiteRegistrationOptions;

/* 
 * Copyright (C) 2015 schurix
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

?>
<h1><?php echo $this->translate('Register'); ?></h1>

<?php if($this->registrationMethodFlag & SiteRegistrationOptions::REGISTRATION_METHOD_MODERATOR_CONFIRM && $this->registrationMethodFlag & SiteRegistrationOptions::REGISTRATION_METHOD_SELF_CONFIRM) : ?>
<p><?php echo $this->translate('Thank you for registering! You should recieve an E-Mail to confirm your E-Mail Address. Once it is confirmed, you will be able to sign in after your account was activated by a moderator') ?></p>
<?php elseif($this->registrationMethodFlag & SiteRegistrationOptions::REGISTRATION_METHOD_MODERATOR_CONFIRM) : ?>
<p><?php echo $this->translate('Thank you for registering! Your account needs to be verified by a moderator before you can sign in. You will be notified when this happens.') ?></p>
<?php elseif($this->registrationMethodFlag & SiteRegistrationOptions::REGISTRATION_METHOD_SELF_CONFIRM) : ?>
<p><?php echo $this->translate('Thank you for registering! You should recieve an E-Mail to confirm your E-Mail Address. Once it is confirmed, you will be able to sign in with your credentials.') ?></p>
<?php endif;
