<?php echo $this->doctype(); ?>
<!--[if lt IE 7]>      <html lang="en" ng-app="myApp" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html lang="en" ng-app="myApp" class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html lang="en" ng-app="myApp" class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> 
<html lang="en" class="no-js"> <!--<![endif]-->
    
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Bubble PLE'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Styles -->
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath('/img/favicon.ico')))
                                        ->prependStylesheet($this->basePath('/css/angular.css')) ?>

        <!-- Scripts -->
        <?php $this->bower('angular', \BowerModule\View\Helper\Bower::CONTAINER_HEAD); ?>
        <?php $this->bower('ieLT9', \BowerModule\View\Helper\Bower::CONTAINER_HEAD); ?>
        <?php echo $this->headScript(); ?> 

    </head>
    
    <body ng-app="myApp" layout="column">
        <md-content layout="column" flex layout-fill>
          <div ng-view layout-fill></div>
        </md-content>
        <script type="text/javascript">
                var applicationBasePath = '<?php echo $this->basePath('/') ?>';
        </script>
        <?php echo $this->inlineScript()
                ->appendFile($this->basePath('/js/angular/app.js'))
                ->appendFile($this->basePath('/js/angular/scripts/controller/nodeCtrl.js'))
                ->appendFile($this->basePath('/js/angular/scripts/controller/courseCtrl.js'))
                ->appendFile($this->basePath('/js/angular/scripts/controller/searchCtrl.js'))
                ->appendFile($this->basePath('/js/angular/scripts/controller/colorChangeCtrl.js'))
                ->appendFile($this->basePath('/js/angular/scripts/controller/dialogCtrl.js'))
                ->appendFile($this->basePath('/js/angular/scripts/configuration.js'))
                ->appendFile($this->basePath('/js/angular/scripts/networkmanager.js'))
                ->appendFile($this->basePath('/js/angular/scripts/utilities.js'))
                ->appendFile($this->basePath('/js/angular/scripts/filemanager.js'))
                ->appendFile($this->basePath('/js/angular/scripts/dialogtemplates.js'))
                ->appendFile($this->basePath('/js/angular/scripts/service/networkService.js'))
                ->appendFile($this->basePath('/js/angular/components/version/version.js'))
                ->appendFile($this->basePath('/js/angular/components/version/version-directive.js'))
                ->appendFile($this->basePath('/js/angular/components/version/interpolate-filter.js'))
        ; ?>
    </body>
</html>
