<?php echo $this->doctype(); ?>

<html lang="en">
	<head>
		<meta charset="utf-8">
		<?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application').' '.$this->translate('Administration'))->setSeparator(' - ')->setAutoEscape(false) ?>

		<?php echo $this->headMeta()
			->appendName('viewport', 'width=device-width, initial-scale=1.0')
			->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
		?>

		<!-- Styles -->
		<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath('/img/favicon.ico')))
						->prependStylesheet($this->basePath('/css/backend.css')) ?>

		<!-- Scripts -->
		<?php $this->bower('backend', \BowerModule\View\Helper\Bower::CONTAINER_HEAD); ?>
		<?php $this->bower('ieLT9', \BowerModule\View\Helper\Bower::CONTAINER_HEAD); ?>
		<?php echo $this->headScript()
				->appendFile($this->basePath('/js/select2.autoload.js')); ?> 

	</head>
	<body>
		<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
			<div class="container">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="<?php echo $this->url('zfcadmin') ?>"><?= $this->translate('Administration') ?></a>
				</div>
				<div class="collapse navbar-collapse">
					<?php
						$navigation = $this->navigation('admin_navigation');
						echo $navigation
								->menu()
								->setMinDepth(0)
								->setMaxDepth(0)
								->setonlyActiveBranch(false)
								->setUlClass('nav navbar-nav')
								->setPartial('partial/navigation.phtml')
								->render(); 
						echo $this->languageSwitch();
					?>
				</div><!--/.nav-collapse -->
			</div>
		</nav>

		<div class="container">
			<?php echo $this->content; ?>
		</div> <!-- /container -->
		<?php echo $this->inlineScript() ?>
	</body>
</html>
