<h3><?php echo sprintf($this->translate('Change Password for %s'), $this->escapeHtml($this->email)); ?></h3>
<?php

$form = $this->resetForm;

$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/resetpassword', array('userId' => $this->userId, 'token' => $this->token)));
$form->setAttribute('method', 'post');

$submitLabel = $form->get('submit')->getLabel();
$form->remove('submit');
$elms = $form->getElements();
foreach($elms as $k => $element){
	/* @var $element \Zend\Form\Element */
	$element
		->setOption('column-size', 'sm-10')
		->setOption('label', $element->getLabel())
		->setLabelAttributes(array('class' => 'col-sm-2'));
}

$form->add(array(
	'name' => 'submit',
	'type' => 'Submit',
	'options' => array(
		'as-group' => true,
	),
	'attributes' => array(
		'value' => $submitLabel,
		'class' => 'btn-success',
	)
));

echo $this->twbForm($form);